In [43]:

import requests
import pandas as pd

# reference internet tutorials and gemini AI for part of code

response = requests.get('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson')
earthquake_data = response.json()
features = earthquake_data['features']
extracted_data = []
for feature in features:
    properties = feature['properties']
    geometry = feature['geometry']

    # Extract required properties
    place = properties.get('place')
    magnitude = properties.get('mag')
    # Convert timestamp to a human-readable date if needed (optional)
    # The 'time' field is in milliseconds since the epoch
    extracted_data.append({
        "Date (MM/DD/YYYY)": date_str,
        "Place": place,
        "Magnitude": magnitude,
    })


df = pd.DataFrame(extracted_data)

print(df.head())

k = df.loc[(df['Magnitude'] > 5)]

k.sort_values(by=['Magnitude'],ascending=False)

  Date (MM/DD/YYYY)                               Place  Magnitude
0        06/18/2025   26 km WNW of Anchor Point, Alaska       1.10
1        06/18/2025   2 km N of Palomar Observatory, CA       0.67
2        06/18/2025  55 km S of Whites City, New Mexico       2.20
3        06/18/2025           11 km SSW of Mariposa, CA       2.37
4        06/18/2025         9 km WNW of San Jacinto, CA       1.12

     Date (MM/DD/YYYY)                                        Place  Magnitude
152         06/18/2025                  southern Mid-Atlantic Ridge        6.2
742         06/18/2025               east of the Philippine Islands        6.2
1436        06/18/2025                   83 km ESE of Nemuro, Japan        6.0
737         06/18/2025  77 km NNE of Punta Cana, Dominican Republic        5.7
741         06/18/2025       105 km SE of Kirakira, Solomon Islands        5.5
2037        06/18/2025     37 km N of Finschhafen, Papua New Guinea        5.5
830         06/18/2025        31 km NNW of Asan-Maina Village, Guam        5.4
389         06/18/2025              270 km SSE of Port Blair, India        5.4
664         06/18/2025                 102 km NNW of Tatsugō, Japan        5.3
299         06/18/2025                    282 km SW of Houma, Tonga        5.3
1051        06/18/2025         80 km ESE of Kimbe, Papua New Guinea        5.3
1456        06/18/2025                12 km NW of Naranjal, Ecuador        5.2
884         06/18/2025                   106 km N of Tatsugō, Japan        5.1
1303        06/18/2025                    93 km N of Tatsugō, Japan        5.1
1321        06/18/2025                    south of the Fiji Islands        5.1
1330        06/18/2025                    south of the Fiji Islands        5.1
1721        06/18/2025                     36 km SW of Semnan, Iran        5.1
1840        06/18/2025           east of the South Sandwich Islands        5.1